name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
<<<<<<< HEAD:.github/workflow/ci.yml
      
=======
>>>>>>> cb962c51226dddd87a766127dc178caf5969e9bf:.github/workflows/kotlin.yml
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble
